POST http://localhost:3000/register
Content-Type: application/json

{
    "username": "kroosadby",
    "email": "krooby@test.csadz",
    "password": "123456"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "krooby@test.cz",
    "password": "123456"
}