import osab from '../assets/img/osab.jpeg'

// temporary array of beatmaps for testing
export const BeatmapArray = [
  {
    id: 1,
    img: osab,
    title: 'aghoj',
    artist: 'nekdo',
    creator: 'Krooby',
    description: 'aaaa',
    difficulty: 'neco',
    downloads: 11,
    dateOfUpload: new Date('2024-02-15'),
  },
  {
    id: 2,
    img: osab,
    title: 'aghoj',
    artist: 'nekdo',
    creator: 'Krooby',
    description: 'aaaa',
    difficulty: 'neco',
    downloads: 11,
    dateOfUpload: new Date('2024-02-15'),
  },
  {
    id: 3,
    img: osab,
    title: 'aghoj',
    artist: 'nekdo',
    creator: 'Krooby',
    description: 'aaaa',
    difficulty: 'neco',
    dateOfUpload: new Date('2024-02-15'),
  },
  {
    id: 4,
    img: osab,
    title: 'aghoj',
    artist: 'nekdo',
    creator: 'Krooby',
    difficulty: 'neco',
    downloads: 11,
    dateOfUpload: new Date('2024-02-15'),
  },
  {
    id: 5,
    img: osab,
    title: 'aghoj',
    artist: 'nekdo',
    creator: 'Krooby',
    description: 'aaaa',
    difficulty: 'neco',
    downloads: 11,
    dateOfUpload: new Date('2024-02-15'),
  },
  {
    id: 6,
    img: osab,
    title: 'aghoj',
    artist: 'nekdo',
    creator: 'Krooby',
    description: 'aaaa',
    difficulty: 'neco',
    downloads: 11,
    dateOfUpload: new Date('2024-02-15'),
  },
]
